### PR TITLE
Fix 132 tags not found

### LINKED ISSUE #132: Tags not found
Hey all,

I'm trying to run gren release against two specific tags and get the following error :

>  Getting all closed Pull RequestsTypeError: Cannot read property '1' of undefined

I think that this is happens because my repository have plenty of tags, and gren doesn't use paging when request tags from github api.

stacktrace:
>   at Gren._callee11$ (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\dist\Gren.js:1189:83)
  at tryCatch (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\regenerator-runtime\runtime.js:62:40)
  at Generator.invoke [as _invoke] (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\regenerator-runtime\runtime.js:296:22)
  at Generator.prototype.(anonymous function) [as next] (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\regenerator-runtime\runtime.js:114:21)
  at step (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
  at C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
  at new Promise (<anonymous>)
  at new F (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\core-js\library\modules\_export.js:35:28)
  at Gren.<anonymous> (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
  at Gren._getClosedIssues (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\dist\Gren.js:1210:31)`

### PR DESCRIPTION
**Pull request by wellDan28**
Close #132 

The resolution contains two parts: 
1.  Enable pagination when two tags were provided in the tags option
2. Validate that the two tags were found (if they were provided)

### CODE REVIEW

**Comment by wellDan28** [comment]
@alexcanessa I don't understand why the codevcov tests are failing, do you have any clue?

**Comment by alexcanessa** [comment]
@wellDan28 I'm trying to understand.

File: lib/src/Gren.js [hunk 1]
```diff
@@ -913,6 +914,27 @@ class Gren {
...
+    _validateRequiredTagsExists(tags, requireTags) {
+        if (requireTags.indexOf('all') >= 0 || !(requireTags instanceof Array)) return;
+
+        const tagsNames = tags.map(x => x.tag.name);
+
+        const missingTags = requireTags.filter(x => tagsNames.indexOf(x) < 0);
+        if (missingTags.length > 0) {
+            const notFoundMessage = (missingTags.length === 1) ? 'tag is' : 'tags are';
+            throw chalk.red(`\nThe following ${notFoundMessage} not found in the repository: ${missingTags}. ` +
+                'please provider tags that are exists in the repository');
```
Comment (alexcanessa) [inline lib/src/Gren.js]: Why not everything in the template literal?

Comment (alexcanessa) [inline lib/src/Gren.js]: Please change so that:

> ~please provider tags that are exists in the repository~ _please provide existing tags._

Comment (wellDan28) [reply lib/src/Gren.js]: I'm sorry, I don't understand, could you please explain what you mean?

File: lib/src/Gren.js [hunk 2]
```diff
@@ -913,6 +914,27 @@ class Gren {
...
+     * @return{}
+     */
+    _validateRequiredTagsExists(tags, requireTags) {
+        if (requireTags.indexOf('all') >= 0 || !(requireTags instanceof Array)) return;
+
+        const tagsNames = tags.map(tagData => tagData.tag.name);
+
+        const missingTags = requireTags.filter(requireTag => tagsNames.indexOf(requireTag) < 0);
+        if (missingTags.length > 0) {
+            const notFoundMessage = (missingTags.length === 1) ? 'tag is' : 'tags are';
```
Comment (alexcanessa) [inline lib/src/Gren.js]: ~`notFoundMessage`~ to `inflection` as it makes more sense 👍

File: lib/src/Gren.js [hunk 3]
```diff
@@ -913,6 +914,27 @@ class Gren {
         );
     }
 
+    /**
+     * Check that the require tags are exists in tags
+     *
+     * @param {Array} tags
+     * @param {any} requireTags
```
Comment (alexcanessa) [inline lib/src/Gren.js]: You can expect `requireTags` to be `Array` because `this.options.tags` it's always an `Array`

https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/lib/src/_utils.js#L123-L149

Also, replace the `@return` with [`@throws`](http://usejsdoc.org/tags-throws.html) as the function is only returning `undefined`

File: lib/src/Gren.js [hunk 4]
```diff
@@ -913,6 +914,27 @@ class Gren {
...
+    _validateRequiredTagsExists(tags, requireTags) {
+        if (requireTags.indexOf('all') >= 0 || !(requireTags instanceof Array)) return;
+
+        const tagsNames = tags.map(tagData => tagData.tag.name);
+
+        const missingTags = requireTags.filter(requireTag => tagsNames.indexOf(requireTag) < 0);
+        if (missingTags.length > 0) {
+            const notFoundMessage = (missingTags.length === 1) ? 'tag is' : 'tags are';
+            throw chalk.red(`\nThe following ${notFoundMessage} not found in the repository: ${missingTags}. ` +
+                'please provide existing tags.');
```
Comment (alexcanessa) [inline lib/src/Gren.js]: Why not one template literal?

**Comment by alexcanessa** [comment]
@all-contributors please add @wellDan28 for bug

**Comment by alexcanessa** [comment]
@all-contributors please add @wellDan28 for code
